-- LiveVoz V11.1 Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,email,display_name)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)))
  on conflict(id) do update set email=excluded.email;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.songs (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  category text not null default 'Personalizada',
  bpm int not null default 100 check (bpm between 30 and 250),
  key text not null default 'C',
  lyrics jsonb not null default '[]'::jsonb,
  chords jsonb not null default '[]'::jsonb,
  cues jsonb not null default '[]'::jsonb,
  transpose_offset int not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.concerts (
  id text primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.concert_members (
  concert_id text not null references public.concerts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'musician' check (role in ('owner','operator','musician','singer')),
  created_at timestamptz not null default now(),
  primary key(concert_id,user_id)
);

create table if not exists public.concert_songs (
  concert_id text not null references public.concerts(id) on delete cascade,
  song_id text not null references public.songs(id) on delete cascade,
  position int not null default 0,
  primary key(concert_id,song_id)
);

create table if not exists public.live_sessions (
  concert_id text primary key references public.concerts(id) on delete cascade,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.backups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.change_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_songs_user on public.songs(user_id);
create index if not exists idx_members_user on public.concert_members(user_id);
create index if not exists idx_history_user_created on public.change_history(user_id,created_at desc);
create index if not exists idx_backups_user_created on public.backups(user_id,created_at desc);

alter table public.profiles enable row level security;
alter table public.songs enable row level security;
alter table public.concerts enable row level security;
alter table public.concert_members enable row level security;
alter table public.concert_songs enable row level security;
alter table public.live_sessions enable row level security;
alter table public.backups enable row level security;
alter table public.change_history enable row level security;

drop policy if exists "profiles read authenticated" on public.profiles;
create policy "profiles read authenticated" on public.profiles for select to authenticated using (true);
drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles for update to authenticated using (id=auth.uid()) with check(id=auth.uid());

drop policy if exists "songs own read" on public.songs;
create policy "songs own read" on public.songs for select to authenticated
using (user_id=auth.uid() or exists(
  select 1 from public.concert_songs cs join public.concert_members cm on cm.concert_id=cs.concert_id
  where cs.song_id=songs.id and cm.user_id=auth.uid()
));
drop policy if exists "songs own write" on public.songs;
create policy "songs own write" on public.songs for all to authenticated
using (user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "concert visible to members" on public.concerts;
create policy "concert visible to members" on public.concerts for select to authenticated
using (owner_id=auth.uid() or exists(select 1 from public.concert_members cm where cm.concert_id=concerts.id and cm.user_id=auth.uid()));
drop policy if exists "concert owner write" on public.concerts;
create policy "concert owner write" on public.concerts for all to authenticated
using (owner_id=auth.uid()) with check(owner_id=auth.uid());

drop policy if exists "members visible" on public.concert_members;
create policy "members visible" on public.concert_members for select to authenticated
using (user_id=auth.uid() or exists(select 1 from public.concerts c where c.id=concert_id and c.owner_id=auth.uid()));
drop policy if exists "members owner manage" on public.concert_members;
create policy "members owner manage" on public.concert_members for all to authenticated
using (exists(select 1 from public.concerts c where c.id=concert_id and c.owner_id=auth.uid()))
with check (exists(select 1 from public.concerts c where c.id=concert_id and c.owner_id=auth.uid()));

drop policy if exists "concert songs visible" on public.concert_songs;
create policy "concert songs visible" on public.concert_songs for select to authenticated
using (exists(select 1 from public.concerts c where c.id=concert_id and (c.owner_id=auth.uid() or exists(select 1 from public.concert_members cm where cm.concert_id=c.id and cm.user_id=auth.uid()))));
drop policy if exists "concert songs owner manage" on public.concert_songs;
create policy "concert songs owner manage" on public.concert_songs for all to authenticated
using (exists(select 1 from public.concerts c where c.id=concert_id and c.owner_id=auth.uid()))
with check (exists(select 1 from public.concerts c where c.id=concert_id and c.owner_id=auth.uid()));

drop policy if exists "live visible to concert" on public.live_sessions;
create policy "live visible to concert" on public.live_sessions for select to authenticated
using (exists(select 1 from public.concerts c where c.id=concert_id and (c.owner_id=auth.uid() or exists(select 1 from public.concert_members cm where cm.concert_id=c.id and cm.user_id=auth.uid()))));
drop policy if exists "live owner host write" on public.live_sessions;
create policy "live owner host write" on public.live_sessions for all to authenticated
using (host_user_id=auth.uid()) with check(host_user_id=auth.uid());

drop policy if exists "backup own" on public.backups;
create policy "backup own" on public.backups for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "history own read" on public.change_history;
create policy "history own read" on public.change_history for select to authenticated using(user_id=auth.uid());
drop policy if exists "history own insert" on public.change_history;
create policy "history own insert" on public.change_history for insert to authenticated with check(user_id=auth.uid());

create or replace function public.share_concert_by_email(p_concert_id text,p_email text,p_role text default 'musician')
returns boolean language plpgsql security definer set search_path=public as $$
declare target_user uuid;
begin
  if not exists(select 1 from public.concerts where id=p_concert_id and owner_id=auth.uid()) then
    raise exception 'No eres propietario de este concierto';
  end if;
  select id into target_user from public.profiles where lower(email)=lower(p_email) limit 1;
  if target_user is null then raise exception 'El usuario todavía no tiene una cuenta LiveVoz'; end if;
  insert into public.concert_members(concert_id,user_id,role)
  values(p_concert_id,target_user,case when p_role in ('operator','musician','singer') then p_role else 'musician' end)
  on conflict(concert_id,user_id) do update set role=excluded.role;
  return true;
end $$;
revoke all on function public.share_concert_by_email(text,text,text) from public;
grant execute on function public.share_concert_by_email(text,text,text) to authenticated;

do $$ begin
  alter publication supabase_realtime add table public.live_sessions;
exception when duplicate_object then null;
end $$;
