-- LiveVoz V14.2 Core Workflow
create extension if not exists pg_trgm;

create table if not exists public.musician_profiles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  instrument text not null default 'guitar',
  instrument_label text not null default 'Guitarra',
  role text not null default 'musician' check (role in ('admin','operator','musician','singer')),
  transpose int not null default 0 check (transpose between -12 and 12),
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.personal_song_notes (
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id text not null references public.songs(id) on delete cascade,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key(user_id,song_id)
);

create table if not exists public.rehearsal_sessions (
  id uuid primary key default gen_random_uuid(),
  concert_id text not null references public.concerts(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.rehearsal_song_status (
  rehearsal_id uuid not null references public.rehearsal_sessions(id) on delete cascade,
  song_id text not null references public.songs(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','review','ready')),
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key(rehearsal_id,song_id)
);

create table if not exists public.concert_activity (
  id bigint generated by default as identity primary key,
  concert_id text not null references public.concerts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_songs_title_trgm on public.songs using gin (title gin_trgm_ops);
create index if not exists idx_songs_category_trgm on public.songs using gin (category gin_trgm_ops);
create index if not exists idx_musician_profiles_owner on public.musician_profiles(owner_id,updated_at desc);
create index if not exists idx_rehearsal_sessions_concert on public.rehearsal_sessions(concert_id,started_at desc);
create index if not exists idx_concert_activity_concert on public.concert_activity(concert_id,created_at desc);

alter table public.musician_profiles enable row level security;
alter table public.personal_song_notes enable row level security;
alter table public.rehearsal_sessions enable row level security;
alter table public.rehearsal_song_status enable row level security;
alter table public.concert_activity enable row level security;

drop policy if exists "musician profiles own" on public.musician_profiles;
create policy "musician profiles own" on public.musician_profiles for all to authenticated
using(owner_id=auth.uid()) with check(owner_id=auth.uid());

drop policy if exists "personal notes own" on public.personal_song_notes;
create policy "personal notes own" on public.personal_song_notes for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "rehearsal sessions visible" on public.rehearsal_sessions;
create policy "rehearsal sessions visible" on public.rehearsal_sessions for select to authenticated
using(owner_id=auth.uid() or exists(
  select 1 from public.concert_members cm
  where cm.concert_id=rehearsal_sessions.concert_id and cm.user_id=auth.uid()
));

drop policy if exists "rehearsal sessions owner write" on public.rehearsal_sessions;
create policy "rehearsal sessions owner write" on public.rehearsal_sessions for all to authenticated
using(owner_id=auth.uid()) with check(owner_id=auth.uid());

drop policy if exists "rehearsal song status visible" on public.rehearsal_song_status;
create policy "rehearsal song status visible" on public.rehearsal_song_status for select to authenticated
using(exists(
  select 1 from public.rehearsal_sessions rs
  where rs.id=rehearsal_id and (rs.owner_id=auth.uid() or exists(
    select 1 from public.concert_members cm where cm.concert_id=rs.concert_id and cm.user_id=auth.uid()
  ))
));

drop policy if exists "rehearsal song status owner write" on public.rehearsal_song_status;
create policy "rehearsal song status owner write" on public.rehearsal_song_status for all to authenticated
using(exists(select 1 from public.rehearsal_sessions rs where rs.id=rehearsal_id and rs.owner_id=auth.uid()))
with check(exists(select 1 from public.rehearsal_sessions rs where rs.id=rehearsal_id and rs.owner_id=auth.uid()));

drop policy if exists "concert activity visible" on public.concert_activity;
create policy "concert activity visible" on public.concert_activity for select to authenticated
using(user_id=auth.uid() or exists(
  select 1 from public.concert_members cm
  where cm.concert_id=concert_activity.concert_id and cm.user_id=auth.uid()
));

drop policy if exists "concert activity own insert" on public.concert_activity;
create policy "concert activity own insert" on public.concert_activity for insert to authenticated
with check(user_id=auth.uid());

create or replace function public.touch_livevoz_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end $$;

drop trigger if exists musician_profiles_touch on public.musician_profiles;
create trigger musician_profiles_touch before update on public.musician_profiles
for each row execute function public.touch_livevoz_updated_at();

drop trigger if exists personal_song_notes_touch on public.personal_song_notes;
create trigger personal_song_notes_touch before update on public.personal_song_notes
for each row execute function public.touch_livevoz_updated_at();